# Production docker-compose with Traefik reverse proxy
# Use with: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.9'

services:
  web:
    # Remove ports - Traefik will route instead
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
    networks:
      - traefik_network

  db:
    networks:
      - traefik_network

  watchtower:
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
